In [1]:
import datasets

In [4]:
mmlu = datasets.load_from_disk('../data/datasets/mmlu.hf')

In [5]:
mmlu

DatasetDict({
    test: Dataset({
        features: ['question', 'subject', 'choices', 'answer'],
        num_rows: 14042
    })
    validation: Dataset({
        features: ['question', 'subject', 'choices', 'answer'],
        num_rows: 1531
    })
    dev: Dataset({
        features: ['question', 'subject', 'choices', 'answer'],
        num_rows: 285
    })
    auxiliary_train: Dataset({
        features: ['question', 'subject', 'choices', 'answer'],
        num_rows: 99842
    })
})

In [7]:
nq = datasets.load_from_disk('../data/datasets/nq.hf')


Loading dataset from disk:   0%|          | 0/287 [00:00<?, ?it/s]

In [8]:
wiki = datasets.load_from_disk('../data/datasets/wiki.hf')


Loading dataset from disk:   0%|          | 0/41 [00:00<?, ?it/s]

In [9]:
nq

DatasetDict({
    train: Dataset({
        features: ['id', 'document', 'question', 'long_answer_candidates', 'annotations'],
        num_rows: 307373
    })
    validation: Dataset({
        features: ['id', 'document', 'question', 'long_answer_candidates', 'annotations'],
        num_rows: 7830
    })
})

In [10]:
wiki

DatasetDict({
    train: Dataset({
        features: ['id', 'url', 'title', 'text'],
        num_rows: 6458670
    })
})

In [12]:
train = wiki['train']

In [13]:
train

Dataset({
    features: ['id', 'url', 'title', 'text'],
    num_rows: 6458670
})

In [14]:
train[0]

{'id': '12',
 'url': 'https://en.wikipedia.org/wiki/Anarchism',
 'title': 'Anarchism',
 'text': 'Anarchism is a political philosophy and movement that is sceptical of authority and rejects all involuntary, coercive forms of hierarchy. Anarchism calls for the abolition of the state, which it holds to be unnecessary, undesirable, and harmful. As a historically left-wing movement, placed on the farthest left of the political spectrum, it is usually described alongside communalism and libertarian Marxism as the libertarian wing (libertarian socialism) of the socialist movement, and has a strong historical association with anti-capitalism and socialism.\n\nHumans lived in societies without formal hierarchies long before the establishment of formal states, realms, or empires. With the rise of organised hierarchical bodies, scepticism toward authority also rose. Although traces of anarchist thought are found throughout history, modern anarchism emerged from the Enlightenment. During the latte

In [15]:
nq['validation'][0]

{'id': '5225754983651766092',
 'document': {'html': '<!DOCTYPE html>\n<HTML class="client-js ve-not-available" lang="en" dir="ltr"><HEAD>\n\n<TITLE>Trade winds - Wikipedia</TITLE>\n\n\n<LINK rel="stylesheet" href="/w/load.php?debug=false&amp;lang=en&amp;modules=ext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediaBadges%7Cmediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.sectionAnchor%7Cmediawiki.skinning.interface%7Cskins.vector.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector" />\n\n<STYLE>\n.referencetooltip{position:absolute;list-style:none;list-style-image:none;opacity:0;font-size:10px;margin:0;z-index:5;padding:0}.referencetooltip li{border:#080086 2px solid;max-width:260px;padding:10px 8px 13px 8px;margin:0px;background-color:#F7F7F7;-webkit-box-shadow:2px 4px 2px rgba(0,0,0,0.3);-moz-box-shadow:2px 4px 2px rgba(0,0,0,0.3);box-shadow:2px 4px 2px rgba(0,0,0,0.3)}.referencetooltip li+li{margin-left:7px;margin-top:-2px

In [20]:
mmlu['test'][2]

{'question': 'Find all zeros in the indicated finite field of the given polynomial with coefficients in that field. x^5 + 3x^3 + x^2 + 2x in Z_5',
 'subject': 'abstract_algebra',
 'choices': ['0', '1', '0,1', '0,4'],
 'answer': 3}

In [22]:
from transformers import AutoModel
from transformers import AutoTokenizer

model = AutoModel.from_pretrained("facebook/contriever") 
tokenizer = AutoTokenizer.from_pretrained("facebook/contriever") #Load the associated tokenizer:

In [23]:

sentences = [
    "Where was Marie Curie born?",
    "Maria Sklodowska, later known as Marie Curie, was born on November 7, 1867.",
    "Born in Paris on 15 May 1859, Pierre Curie was the son of Eugène Curie, a doctor of French Catholic origin from Alsace."
]

inputs = tokenizer(sentences, padding=True, truncation=True, return_tensors="pt")
embeddings = model(**inputs)

In [32]:
embeddings[0].shape

torch.Size([3, 30, 768])

In [35]:
inputs['input_ids'].shape

torch.Size([3, 30])

In [48]:
all = embeddings[0][0]

In [49]:
last = embeddings[1][0]

In [50]:
last.shape

torch.Size([768])

In [51]:
all = all.mean(dim=0)

In [52]:
all.shape

torch.Size([768])

In [53]:
all == last

tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, 

In [54]:
all

tensor([ 1.0148e-01, -3.5126e-01, -7.1869e-02,  8.9796e-02,  1.5774e-02,
        -1.2822e-01,  3.7416e-02, -2.1790e-01, -1.0529e-01, -5.3376e-02,
         1.1489e-01,  2.9131e-01, -2.5046e-02,  5.2447e-03,  2.3257e-01,
        -4.6217e-02,  1.7297e-01,  1.3147e-01,  2.6280e-01,  1.9332e-01,
        -8.0924e-02, -1.1887e-01, -8.4145e-02,  1.0096e-01, -4.9441e-02,
         1.3808e-01, -3.5788e-02, -7.5221e-02, -2.2511e-01,  1.0894e-01,
         2.3336e-02,  8.1270e-02,  1.2158e-01, -2.7296e-01, -9.3815e-02,
         2.3892e-01, -1.6733e-01, -6.1704e-02, -2.8500e-03,  1.4344e-01,
         1.5473e-01,  2.6049e-01,  1.1539e-01,  5.8998e-02, -4.7693e-02,
        -1.0090e-01, -3.6722e-04,  2.9151e-01, -6.3820e-02, -2.5738e-01,
        -1.5030e-01,  6.1501e-02,  1.7328e-01,  6.2028e-02, -2.1143e-01,
         4.5739e-02, -4.9367e-02, -5.1597e-02, -8.8556e-02,  9.5114e-02,
        -1.0843e-02, -9.0101e-02, -7.0806e-03, -3.0311e-01,  8.6490e-02,
         3.9277e-01,  6.3248e-02,  2.3978e-01, -2.9

In [55]:
last

tensor([ 2.0452e-03, -9.0742e-03,  5.8498e-04, -1.6010e-02, -1.2389e-02,
        -1.5275e-03,  1.2241e-02,  6.6956e-03,  2.6529e-02, -2.4753e-01,
         2.1253e-02, -1.3548e-02,  8.0262e-02, -3.4218e-02,  4.2722e-02,
         1.5033e-02,  5.5678e-02, -1.6113e-02,  1.5280e-02,  1.0128e-02,
         2.9256e-02,  1.4836e-01,  2.5578e-02,  3.5175e-02,  1.9802e-02,
        -2.4535e-02, -1.4111e-02,  7.9551e-02,  4.1814e-02,  2.6857e-02,
         3.4172e-03, -7.6247e-03, -7.9172e-02, -1.8377e-02, -4.9589e-02,
        -1.5011e-01, -2.8727e-03, -2.3024e-02,  2.5949e-03, -4.2032e-03,
        -5.0843e-02,  4.8515e-04,  1.7187e-01, -7.5673e-02, -9.9479e-03,
        -3.0660e-02, -1.1981e-01, -4.8381e-03, -2.3297e-02, -5.1048e-02,
        -1.4718e-02, -5.3915e-02,  1.0032e-02,  6.6365e-03,  1.6001e-02,
         3.4595e-02, -1.5262e-02, -3.9668e-03, -1.3962e-02, -5.8577e-02,
        -4.4443e-02,  7.6575e-03,  3.3753e-02, -5.2009e-02, -3.5857e-02,
        -3.4944e-02,  3.1971e-03, -5.9062e-03,  1.9

In [58]:
res = embeddings.last_hidden_state.mean(dim=1)

In [59]:
res.shape

torch.Size([3, 768])

In [ ]:
def exact_match_score(predictions, references):
    """
    Calculates the Exact Match (EM) score between predictions and references.

    Args:
        predictions (list of str): List of predicted answers.
        references (list of str): List of reference (correct) answers.

    Returns:
        float: Exact Match score as a percentage.
    """
    if len(predictions) != len(references):
        raise ValueError("The number of predictions and references must be the same.")

    exact_matches = sum(pred == ref for pred, ref in zip(predictions, references))
    total = len(references)
    em_score = (exact_matches / total) * 100
    return em_score

# Example usage:
predictions = ["The capital of France is Paris.", "The largest planet is Jupiter."]
references = ["The capital of France is Paris.", "The largest planet is Jupiter."]
score = exact_match_score(predictions, references)
print(f"Exact Match Score: {score:.2f}%")
